### ISSUE TITLE
OrcishOpenAIService  - 504 Gateway Timeout in project deployed to Vercel 

### ISSUE THREAD

**Issue by franky358** [TheOrcDev/orcish-openai-connector#1]
Hi there.

How could I  fix this error in a Next 14 web app deployed to Vercel?
"504 Gateway Timeout"
"Task timed out after 10.01 seconds"

Working well in local but getting the error in production.

`"use server";

import { OrcishOpenAIService } from "orcish-openai-connector";

if (!process.env.OPENAI_API_KEY) {
  throw "No OpenAI Key";
}

const orcishOpenAIService = new OrcishOpenAIService({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function getDalle3Result(prompt: string) {
  return await orcishOpenAIService.getDalle3Image(prompt, {
    imageResolution: "1024x1024",
  });
}
`

**Comment by TheOrcDev** [comment]
> Hi there.
> 
> How could I fix this error in a Next 14 web app deployed to Vercel? "504 Gateway Timeout" "Task timed out after 10.01 seconds"
> 
> Working well in local but getting the error in production.
> 
> `"use server";
> 
> import { OrcishOpenAIService } from "orcish-openai-connector";
> 
> if (!process.env.OPENAI_API_KEY) { throw "No OpenAI Key"; }
> 
> const orcishOpenAIService = new OrcishOpenAIService({ apiKey: process.env.OPENAI_API_KEY, });
> 
> export async function getDalle3Result(prompt: string) { return await orcishOpenAIService.getDalle3Image(prompt, { imageResolution: "1024x1024", }); } `

Hello there! The code looks fine.

Did you set your environment variables correctly on Vercel? Can you try `console.log(process.env.OPENAI_API_KEY)`?

**Comment by franky358** [comment]
Hi @TheOrcDev 
It's a vercel issue with projects on the hobby tier making api calls that takes more than 10 seconds to resolve, look at this:
https://www.reddit.com/r/nextjs/comments/1aim533/are_you_able_to_solve_the_timeout_issue_in_vercel/
https://www.reddit.com/r/nextjs/comments/193hgj6/nextjs_vercel_error_504s/

I ended up using server sent events to handle the requests:
https://github.com/Neo-Ciber94/next-server-task?tab=readme-ov-file

Thanks @TheOrcDev  for putting work on this package and in your YouTube channel!

**Comment by TheOrcDev** [comment]
> Hi @TheOrcDev It's a vercel issue with projects on the hobby tier making api calls that takes more than 10 seconds to resolve, look at this: https://www.reddit.com/r/nextjs/comments/1aim533/are_you_able_to_solve_the_timeout_issue_in_vercel/ https://www.reddit.com/r/nextjs/comments/193hgj6/nextjs_vercel_error_504s/
> 
> I ended up using server sent events to handle the requests: https://github.com/Neo-Ciber94/next-server-task?tab=readme-ov-file
> 
> Thanks @TheOrcDev for putting work on this package and in your YouTube channel!

You're welcome! Thank you for the kind words!

I'm glad you figured out what's wrong!
